### ISSUE TITLE
Etiquettes imprimante Thermique

### ISSUE THREAD

**Issue by Astro1295** [fondationmerieux/labbook_python#3]
Bonjour, 

Je suis entrain de tester une imprimante thermique XP-Q260III pour imprimer mes étiquette mais vous avez que du PDF en format A4 sur votre ISO. 

Comment faire pour imprimer des étiquettes de 80mm avec un nombre de 4 ou 6 étiquettes uniquement ? 

J'ai vu des model de document sur la version de demo mais pas sur l'ISO ni le code source. 

Merci à vous

**Comment by labbook-fmx** [comment]
Bonjour,

Bravo pour avoir vu tout cela !
Cela fait très plaisir de voir que vous êtes intéressé par le projet LabBook.
Puis je savoir dans quel contexte vous voudriez l'utiliser?

Nous avons lancé LabBook 3.0 l'été 2021; et nous lançons en ce moment LabBook 3.1 (principalement pour un support multilingue de l'interface).
Mais l'équipe travaille en ce moment sur LabBook 3.2
qui va permettre en effet de compléter le système d'étiquette.
Pour le moment, nous avons des étiquettes très simple et avec LabBook 3.2 nous aurons le choix entre 2 types d'étiquette.
Toutefois, nous restons pour le moment sur des planches A4 car il existe trop de type d'imprimante thermique, il est dur à notre niveau de toutes les prendre en charge.

Je passe la main à l'équipe de développement pour qu'ils puissent vous répondre sur le fait qu'il soit possible ou non de modifier le format avec les évolutions de LabBook 3.2.

Amicalement
Nicolas Steenkeste

**Comment by aegleinformatiquemedicale** [comment]
Bonjour,

Il sera possible de faire le format que vous souhaitez dans la version 3.2 car le format dépendra du modèle que vous aurez construit, celui fourni avec la version sera en A4.

Pour préciser aussi "nous aurons le choix entre 2 types d'étiquette", l'application sort un nombre de donnes possibles d'intégrer dans un modèle d'étiquette dont 2 format  de "code barre", code39 et QR code.

Cordialement
Alexandre
