### ISSUE TITLE
Déployer Labbook sur un serveur live

### ISSUE THREAD

**Issue by Hodaifa98** [fondationmerieux/labbook_python#4]
Bonjour, comment puis-je déployer Labbook sur un serveur live ? Il fonctionne toujours avec localhost:5000 mais cela ne fonctionne pas : "net::ERR_CONNECTION_REFUSED"

**Comment by labbook-fmx** [comment]
Bonjour,

L'équipe informatique de LabBook va pouvoir vous répondre après la pause pour les fêtes de fin d'année.
Toutefois, je souhaite souligner que LabBook est distribué sous forme d'un ISO que vous pouvez télécharger sur le site : https://www.lab-book.org/
Nous avons une démo live : https://demo.lab-book.org/sigl 
ATTENTION : La base de données est effacée tous les soirs.

Des comptes sont à votre disposition :
Un compte administrateur; Login : root / Password : root
Un compte biologiste; Login : biologiste / Password : biologiste
Un compte technicien; Login : technicien / Password : technicien
Un compte secrétaire; Login : secretaire / Password : secretaire
Un compte prescripteur; Login : prescripteur / Password : prescripteur
Un Compte qualiticien; Login : qualiticien / Password : qualiticien

Mais aussi des comptes avec des variations dans les droits d'accès :
Un compte technicien avancé; Login : techav / Password : techav
Un compte technicien qualiticien; Login : techq / Password : techq
Un compte secrétaire avancé; Login : secrav / Password : secrav

Cette installation est là uniquement pour une démo, nous ne recommandons pas l'utilisation de LabBook à partir d'une installation sur internet; mais bien avec une installation locale à partir de l'ISO.
En effet, LabBook n'est pas un logiciel comme un autre, c'est un LIS qui se doit de protéger la confidentialité et la sécurité des données de patient du laboratoire.
En utilisant l'ISO, vous avez une installation sécurisée et qui garanti cela.

Pour les autres questions techniques, je passe la main à mes collègues informaticiens.

PS : nous sommes en train de mettre à jour le site internet de LabBook pour mettre en téléchargement LabBook 3.1

Amicalement
Nicolas Steenkeste

**Comment by phb95** [comment]
Bonjour,

Effectivement, ce dépôt ne permet pas directement d'installer une version de production. L'installation décrite est destinée au développement seulement.

Le cas d'usage de LabBook tel que mis en oeuvre dans l'ISO, c'est plutôt une installation sur quelques postes dans un LAN. Mais rien n'empêche dans le principe de le faire fonctionner derrière un serveur web de production sur https, comme c'est le cas pour le [site de démo](https://demo.lab-book.org/sigl). Il faut naturellement dans ce cas que vous gériez les certificats nécessaires.

Quelle est la configuration que vous envisagez ?

**Comment by aegleinformatiquemedicale** [comment]
Bonjour,

Effectivement, ce dépôt ne permet pas directement d'installer une version de production. L'installation décrite est destinée au développement seulement.

Le cas d'usage de LabBook tel que mis en oeuvre dans l'ISO, c'est plutôt une installation sur quelques postes dans un LAN. Mais rien n'empêche dans le principe de le faire fonctionner derrière un serveur web de production sur https, comme c'est le cas pour le site de démo. Il faut naturellement dans ce cas que vous gériez les certificats nécessaires.

Quelle est la configuration que vous envisagez ?

**Comment by Astro1295** [comment]
> Bonjour,
> 
> Effectivement, ce dépôt ne permet pas directement d'installer une version de production. L'installation décrite est destinée au développement seulement.
> 
> Le cas d'usage de LabBook tel que mis en oeuvre dans l'ISO, c'est plutôt une installation sur quelques postes dans un LAN. Mais rien n'empêche dans le principe de le faire fonctionner derrière un serveur web de production sur https, comme c'est le cas pour le site de démo. Il faut naturellement dans ce cas que vous gériez les certificats nécessaires.
> 
> Quelle est la configuration que vous envisagez ?

Bonjour, 

Je suis entrain de faire lm'installation dans un mini-laboratoire dans un village en Algérie dans un mini-LAN avec box internet. Je suis preneur de la configuration nécessaire pour un certificat auto-signé directement sur le LAN. 

Je vais faire une ouverture de port ensuite pour un accès distant en passant par une protection DDos sur CloudFlare 

Quelles sont les commande nécessaire pour ajouter le certificat sur le container serveur web ? :) 
Merci par avance

**Comment by labbook-fmx** [comment]
Je ne peux que vous encourager à passer par notre ISO, actuellement sur le site internet c'est l'ISO de la 3.0.13 qui est en téléchargement mais la 3.1.15 sera chargé d'ici la fin de semaine.
Il vous suffit de dédier un ordinateur pour faire cette installation puis vous pouvez l'utiliser en monoposte ou en réseau en appelant l'IP dans n'importe quel navigateur d'un ordi de votre réseau intranet du labo.

* Avec l'ISO, vous aurez aussi accès à notre système de backup qui sécurise votre base de données sur un périphérique USB et donc permet une restauration très facile; Avec votre installation, je ne sais pas si le système de backup sera fonctionnel.
* Avec l'ISO, vous avez aussi accès à tous les e-learning de la Fondation Mérieux chargé directement dans l'ordinateur. Donc le personnel de laboratoire peut faire de la formation continue grâce à LabBook.

Amicalement
Nicolas

**Comment by Hodaifa98** [comment]
> Quelle est la configuration que vous envisagez ?

J'ai un serveur Ubuntu et je souhaite rendre labbook disponible pour les connexions à distance. Je ne peux pas utiliser l'ISO, et lorsque j'essaie de déployer labook, il répond aux requêtes sur 127.0.0.1:5000 ; mais je veux que les requêtes soient envoyées à mon serveur Web.

**Comment by labbook-fmx** [comment]
L'installation de LabBook par l'ISO est en effet prévu pour un déploiement sur un réseau intranet, pas sur un serveur web. Le fonctionnement sur serveur web est possible ( c'est le cas de notre démo : https://demo.lab-book.org/sigl ); mais nous privilégions l'utilisation en réseau local pour un usage en routine. En effet, LabBook contient des données de santé sensibles et nous privilégions la confidentialité et protection des données.

**Comment by aegleinformatiquemedicale** [comment]
Nous faisons quelques tests avant de vous répondre sur l'accès depuis le web.

Sinon vous indiquez :

> je souhaite rendre labbook disponible pour les connexions à distance

Peut-être cet usage à distance concerne un groupe restreint de personnes ? Le cas échéant avez-vous envisagé la piste d'une connexion VPN ?
