### ISSUE TITLE
Erreur 400: services/analysis/det/0:1

### ISSUE THREAD

**Issue by Hodaifa98** [fondationmerieux/labbook_python#5]
Lors de l'ajout d'une analyse, j'obtiens cette erreur:

![Capture](https://user-images.githubusercontent.com/40869908/147891787-3a72351a-7212-474c-a1c1-e4849d7c5577.PNG)

**Comment by labbook-fmx** [comment]
Merci pour votre message.
Ce bug a été identifié et corrigé.
Ici vous étiez sur la 3.1.4 de démo.

Nous sommes en train de mettre à jour le site internet de LabBook pour permettre le téléchargement de l'ISO de LabBook 3.1.5 (cela sera fait dans la semaine)
et nous avons maintenant lancé le développement de LabBook 3.2 dont une démo partielle est déjà disponible : https://demo.lab-book.org/sigl

**Comment by Hodaifa98** [comment]
Merci de votre réponse rapide. Qu'en est-il de ce repo ? Allez-vous également le mettre à jour avec la dernière version de labbook ?
Je préfère héberger ma propre application directement sans l'iso.
Merci!

**Comment by labbook-fmx** [comment]
Le repo est mis à jour version après version.
Vous disposez ici du code de la version 3.1.5

**Comment by aegleinformatiquemedicale** [comment]
La version 3.1.5 est disponible.

Cordialement
Alexandre
