### ISSUE TITLE
Finalisation initialisation

### ISSUE THREAD

**Issue by rkhcisse** [fondationmerieux/labbook_python#6]
Bonjour
J'ai déployé labbook sur mon espace aws mais j'ai toujours ce probleme d'initialisation comme sur la capture
![IMG-20240605-WA0012](https://github.com/fondationmerieux/labbook_python/assets/174335896/a91bfcf2-6f38-4831-9a17-95a3de60201c)

Je vous remercie par avance pour votre aide afin que je puisse avancer

**Comment by aegleinformatiquemedicale** [comment]
Bonjour,
Ce message est le message générique en cas d'erreur d'accès au backend ou à la base de donnée par exemple.
Merci de nous en dire un peu plus sur votre installation.

**Comment by rkhcisse** [comment]
Merci pour votre promptitude
Mon collaborateur ,Mr NDIAYE en copie du mail apportera plus de précisions

Rokhaya B. CISSE
Ingénieur en informatique
Chef du service informatique
UCAD/FMPOS
00221781297940
________________________________
De : aegleinformatiquemedicale ***@***.***>
Envoyé : lundi 1 juillet 2024 13:57
À : fondationmerieux/labbook_python ***@***.***>
Cc : Rokhaya Ba CISSE ***@***.***>; Author ***@***.***>
Objet : Re: [fondationmerieux/labbook_python] Finalisation initialisation (Issue #6)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>

Bonjour,
Ce message est le message générique en cas d'erreur d'accès au backend ou à la base de donnée par exemple.
Merci de nous en dire un peu plus sur votre installation.

**Comment by labbook-fmx** [comment]
Bonjour a tous,

Vous pouvez vous installer LabBook pour faire une démo sur un serveur aws. Mais nous ne recommandons pas l utilisation en routine pour un laboratoire. LabBook a été développé pour une installation sur un serveur local.
Dans le futur, nous aurons l arrivée de oauth et hpps par défaut mais aussi d autres fonctions pour effectivement tourner en routine sur serveur cloud.

Amicalement
Nicolas

Fondation Mérieux
17 rue Bourgelat
Lyon, France
________________________________

**Comment by rkhcisse** [comment]
Merci encore pour votre aide
Nous n'avons pas rencontré de problèmes spécifiques lors de l'installation. La base de données se connecte correctement au serveur par contre nous avons pensé que le lien de téléchargement GitHub n'est pas mis a jour et que cela pourrait être la cause
